### ISSUE TITLE
Roadmap for the static scheduling infrastructure

### ISSUE THREAD

**Issue by jopperm** [llvm/circt#1393]
### Modeling of problems
- [x] **Basic**: Operators have an integer latency. Solution: Integer start times for all operations.
   #1268
   #1392
- [x] **Cyclic** extends **Basic**: Dependences may have a distance. Solution: Initiation interval (II).
   #1476
- [x] **SharedOperators** extends **Basic**: Operator types may have a limited number of instances, and each instance can handle a different operation in every time step.
   #1552
- [x] **Chaining** extends **Basic**: Models the accumulation of physical propagation delays on combinational paths along SSA dependences.
   #2233
- [ ] **PartiallyPipelinedOperators** extends **Basic**: Operator types have a blocking time, i.e. the II of the operator module/functional unit.
- [x] **Modulo** extends **Cyclic**, **SharedOperators**: Composition of the two base problems.
   #1886

### Algorithms
- [x] List scheduler for the **Basic** problem.
   #1358
- [x] Simplex-based scheduler for **Basic** and **Cyclic** problems.
   #1526
   #1535 
- [x] Heuristic algorithm (also based on the simplex scheduler) for the **SharedOperators** problem.
   #1620
   #1621 
   #1622
- [x] Heuristic algorithm (also based on the simplex scheduler) for the **Modulo** problem.
   #2258
   #2396
   #2397
- [x] Scheduler for the **Chaining** problem with strict cycle-time constraints.
   #2557

### Utilities
*(no specific plans/order yet)* Examples: cycle enumerator, modulo reservation table, ... 

### External tools
- [x] Add optional support for [Google OR tools](https://developers.google.com/optimization/)
   https://github.com/circt/images/pull/13
   #2465 

*Let me know if you are interested in a specific problem/algorithm, I'm happy to reprioritize!*

**Comment by mikeurbach** [comment]
Regarding cycle detection, I saw @hanchenye recently started an analysis to detect combinational cycles in the FIRRTL dialect: https://github.com/llvm/circt/pull/1388. There is also a pass in the Handshake dialect that we've both had our hands on, which has the ability to look for cycles in the dataflow in order to insert buffers: https://github.com/llvm/circt/blob/037ab746e4e639df96f6eae4b8342d776122e00e/lib/Conversion/StandardToHandshake/StandardToHandshake.cpp#L1511.

I wonder if we can standardize these into a generic cycle detection utility. I'm wondering if it can be done generically on opaque `Operation *`s... If not, it seems like a good candidate for some OpInterface(s) somewhere, to guide such a utility.

**Comment by hanchenye** [comment]
@mikeurbach There're some infrastructures in LLVM, [GraphTraits](https://llvm.org/doxygen/GraphTraits_8h_source.html) and [SCCIterator](https://llvm.org/doxygen/SCCIterator_8h_source.html), for creating a view of graph on top of the IR and iterating on SCCs. This should work well on graph regions, such as handshake function.

**Comment by jopperm** [comment]
Oh the SCC iterators look very promising, should be straightforward to define the graph traits on top of scheduling problem. Thanks!

**Comment by mikeurbach** [comment]
Interesting, that's good to know!

**Comment by jopperm** [comment]
Retiring this generic tracker because most of the initial vision for the infra has been fleshed out. Future projects (problems, algorithms, integrations, ...) should just use their own issues/PRs/... and the [Scheduling] label.
