### ISSUE TITLE
canonicalization of RTL variadic operations

### ISSUE THREAD

**Issue by drom** [llvm/circt#33]
https://mlir.llvm.org/docs/Canonicalization

### and
 * [x] `and(x) -> x` -- noop [#38]
 * [x] `and(..., 0) -> 0` -- annulment  [#38]
 * [x] `and(..., '1) -> and(...)` -- identity [#40]
 * [x] `and(..., x, x) -> and(..., x)` -- idempotent [#85]
 * [x] `and(..., c1, c2) -> and(..., c3)` where  `c3 = c1 & c2` -- constant folding  [#91]
 * [x] `and(x, and(...)) -> and(x, ...)` -- flatten [#114]
 * [ ] `and(..., x, not(x)) -> and(..., 0)` -- complement

### or
 * [x] `or(x) -> x` -- noop  [#38]
 * [x] `or(..., '1) -> '1`  -- annulment  [#38]
 * [x] `or(..., 0) -> or(...)` -- identity [#40]
 * [x] `or(..., x, x) -> or(..., x)` -- idempotent [#114]
 * [x] `or(..., c1, c2) -> or(..., c3)` where  `c3 = c1 | c2` -- constant folding [#120]
 * [x] `or(x, or(...)) -> or(x, ...)` -- flatten [#121]
 * [ ] `or(..., x, not(x)) -> or(..., '1)` -- complement

### xor
 * [x] `xor(x) -> x` -- noop  [#38]
 * [x] `xor(..., 0) -> xor(...)` -- identity [#40]
 * [ ] `xor(..., '1) -> not(xor(...))`
 * [x] `xor(..., x, x) -> xor(..., 0)` -- idempotent? [#114]
 * [x] `xor(..., c1, c2) -> xor(..., c3)` where  `c3 = c1 ^ c2` -- constant folding [#120]
 * [x] `xor(x, xor(...)) -> xor(x, ...)` -- flatten [#121]
 * [ ] `xor(..., x, not(x)) -> xor(..., '1)`

### add
 * [x] `add(x) -> x` -- noop  [#38]
 * [x] `add(..., 0) -> add(...)` -- identity [#40]
 * [x] `add(..., x, x) -> add(..., shl(x, 1))` [#154]
 * [x] `add(..., c1, c2) -> add(..., c3)` where  `c3 = c1 + c2` -- constant folding [#120]
 * [x] `add(x, add(...)) -> add(x, ...)` -- flatten [#121]

### mul
 * [x] `mul(x) -> x` -- noop  [#38]
 * [x] `mul(..., 0) -> 0` -- annulment  [#38]
 * [x] `mul(..., 1) -> mul(...)` -- identity [#40]
 * [x] `mul(..., c1, c2) -> mul(..., c3)` where  `c3 = c1 * c2` -- constant folding [#120]
 * [x] `mul(a, mul(...)) -> mul(a, ...)` -- flatten [#121]

**Comment by uenoku** [comment]
Is there NotOp in RTL dialect now?(Sorry if I am missing)

**Comment by lattner** [comment]
`not(x)` is expressible as `xor(x, -1)`

**Comment by uenoku** [comment]
Thanks, since `not` is in the list above, I thought it is defined as Op somewhere.

**Comment by drom** [comment]
we should have `rtl.not` Op #300

**Comment by drom** [comment]
LGTM
