### ISSUE TITLE
[HW][InnerSym] Use Inner* infra, enable verification, support IST on HW... (tracking issue)

### ISSUE THREAD

**Issue by dtzSiFive** [llvm/circt#4453]
There's work to be done regarding InnerSymbols throughout, this issue is to track known tasks and problems, and is intended to be maintained as work on this progresses.

## Tasks

* [ ] Make HWModuleLike's IST's
  * IST is an HW interface yet none of its operations use it yet.
* [ ] Use IRN in HW, now that it's defined there
  * [ ] Add to container op (perhaps move off `builtin.module`?), or maybe make `builtin.module` (optionally? (!)) an IRN.
    * Changing the 'container' op is a big change and should not be done without some discussion/review.
* [ ] Enable verification of inner_syms in HW (#3526).  Using IRN (+IST) in HW will accomplish this.
  * [ ] Audit all users of InnerRef to ensure they work with this and implement `InnerRefUserOpInterface` where appropriate (for verification).
  * [ ] Audit any existing verifiers that should instead use the more efficient verification enabled by IRN/IST.
* [ ] Move InnerSymDCE to HW, it's no longer FIRRTL-specific (especially after #4418 which may also do this).
* [ ] Review whether IST can replace HWSymCache or otherwise share code.
* [ ] Review documentation reflects current situation (as needed)
  * [ ] HW's rationale docs on ["Symbols and Visibility"](https://github.com/llvm/circt/blob/main/docs/Dialects/HW/RationaleHW.md#symbols-and-visibility) does not seem accurate (and not due to any recent change).
* [ ] Review and be clear about differences between `hw::InnerRefAttr` and `hw::HWInnerRefAttr`.
  * I believe the latter is for representing inner references in other dialects? Comments on its introduction: https://github.com/llvm/circt/pull/3005#discussion_r862374300 .
* [ ] Drop InnerRefRecord as unused

## Abbreviations

IST: InnerSymbolTable
IRN: InnerRefNamespace
